### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shubhank-saxena** [ceramicstudio/dynamic-nft-example#2]
# Description

I started the server as per instructions, but I am getting the following error.
![Screenshot 2022-08-12 at 5 33 37 PM](https://user-images.githubusercontent.com/29003047/184350186-6bcbe345-223e-4b5e-bd71-abae847937c8.png)

# Technical Information

Running this on Mac M1 Air

**Comment by ukstv** [comment]
The project is not really maintained. It uses package dependencies, that are not guaranteed to work.

On M1 too, I can see the same error. After I restart process and run it again via `pnpm run dev`, the project still works, no errors thrown.

**Comment by shubhank-saxena** [comment]
Works like a charm! Thank you @ukstv
